version: '2'
services:
    soclejhipster-app:
        image: soclejhipster
        external_links:
            - soclejhipster-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/soclejhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10
        ports:
            - 8080:8080
    soclejhipster-mysql:
        container_name: soclejhipster-mysql
        image: mysql:5.7.13
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=soclejhipster
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8
    


